# Generated by Django 4.1.4 on 2023-02-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=18)),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('complemento', models.CharField(max_length=255, verbose_name='Complemento')),
                ('ponto_referencia', models.CharField(max_length=255, verbose_name='Ponto de referência')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('whatsapp', models.BooleanField(blank=True, verbose_name='Whatsapp')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
    ]
