# Generated by Django 4.1.4 on 2023-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='E-mail para contato'),
        ),
    ]
