# Generated by Django 4.1.4 on 2023-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.BooleanField(blank=True, verbose_name='Esse telefone é Whatsapp?'),
        ),
    ]
